export const USER_LOCAL_LOGIN = 'USER_LOCAL_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_GET_CONFIG = 'USER_GET_CONFIG';
export const SELECT_TRAINLINE = 'SELECT_TRAINLINE';
export const CLEAN_STATE = 'CLEAN_STATE';
